name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.8'
        environment-file: environment.yml
        activate-environment: prepare_new_ops

    - name: Run pytest
      run: |
        conda activate prepare_new_ops
        cd unit_test
        pytest --rootdir=/unit_test/*
