name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Run tests
      run: |
        conda install pytest
        cd unit_test
        pytest --rootdir=unit_test

    - name: Clean up
      run: |
        conda deactivate
        conda env remove -n prepare_new_ops
