name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.8'
        environment-file: environment.yml
        activate-environment: prepare_new_ops

    - name: Verify Conda environment
      run: |
        conda info
        conda list

    - name: Run pytest
      run: |
        # Ensure Conda environment is activated
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate prepare_new_ops
        
        # Navigate to the unit_test directory
        cd unit_test
        
        # Run pytest
        pytest --rootdir=/unit_test
