name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.8'
        environment-file: environment.yml
        activate-environment: prepare_new_ops

    - name: Verify Conda environment
      run: |
        conda info
        conda list

    - name: Set environment variables
      run: echo "FOLDER_GOLD_PATH=$(pwd)../airflow/data/gold" >> $GITHUB_ENV

    - name: Run pytest
      env:
        FOLDER_GOLD_PATH: ${{ env.FOLDER_GOLD_PATH }}
      run: |
        # Source Conda profile script to enable Conda commands
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate prepare_new_ops
        
        # Navigate to the unit_test directory and run pytest
        cd unit_test
        pytest *