name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.8'
        environment-file: environment.yml
        activate-environment: prepare_new_ops

    - name: Verify Conda environment
      run: |
        conda info
        conda list

    - name: Run pytest
      run: |
        # Source Conda profile script to enable Conda commands
        source $(conda info --base)/etc/profile.d/conda.sh
        pip install -r requirements.txt
        # Run pytest within the Conda environment
        pytest unit_test/*

    - name: Clean up
      run: |
        conda deactivate
        conda env remove -n prepare_new_ops
